// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"database/sql"
)

type Key struct {
	ID     string
	Hashed string
	Admin  sql.NullBool
}

type Url struct {
	ID  string
	Url string
}

type Vanity struct {
	ID  string
	Url string
}
